# 尝试执行打印num，捕获Exception
try:
    print(num)
except Exception as result:
    print(result)